spring.application.name=api
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=60

app.dev.user.cpf=${DEV_USER_CPF:}
app.dev.user.nome=${DEV_USER_NAME:}
app.dev.user.password=${DEV_USER_PASSWORD:}

app.dev.medico.cpf=${DEV_MEDICO_CPF:}
app.dev.medico.nome=${DEV_MEDICO_NAME:}
app.dev.medico.password=${DEV_MEDICO_PASSWORD:}