name: Build

on:
  pull_request:
    branches:
      - develop
      - 'feature/**'
  push:
    branches:
      - develop
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build com Maven
        run: mvn -B clean package